[package]
name = "sdkwork-api-whatseek-assembly"
edition = "2021"
version = "0.1.0"
description = "Generated API assembly for sdkwork-whatseek application HTTP plane."

[lints]
workspace = true

[lib]
name = "sdkwork_api_whatseek_assembly"
path = "src/lib.rs"

[dependencies]
axum = "0.8"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
sdkwork-web-bootstrap = { path = "../../../sdkwork-web-framework/crates/sdkwork-web-bootstrap" }
sdkwork-web-core = { path = "../../../sdkwork-web-framework/crates/sdkwork-web-core" }
