import type { AppCategory, WhatseekApp } from '../types.js';

/**
 * Phase 1 catalog data (PRD §14 categories, §16 detail fields). The category
 * labels resolve through i18n keys (`labelKey`); everything else is
 * locale-neutral catalog content seeded for the standalone milestone.
 */

export const WHATSEEK_CATEGORIES: readonly AppCategory[] = [
  { id: 'efficiency', labelKey: 'whatseek.apps.category.efficiency', icon: '⚡' },
  { id: 'office', labelKey: 'whatseek.apps.category.office', icon: '🗂️' },
  { id: 'coding', labelKey: 'whatseek.apps.category.coding', icon: '💻' },
  { id: 'design', labelKey: 'whatseek.apps.category.design', icon: '🎨' },
  { id: 'image', labelKey: 'whatseek.apps.category.image', icon: '🖼️' },
  { id: 'video', labelKey: 'whatseek.apps.category.video', icon: '🎬' },
  { id: 'audio', labelKey: 'whatseek.apps.category.audio', icon: '🎧' },
  { id: 'ecommerce', labelKey: 'whatseek.apps.category.ecommerce', icon: '🛒' },
  { id: 'marketing', labelKey: 'whatseek.apps.category.marketing', icon: '📣' },
  { id: 'education', labelKey: 'whatseek.apps.category.education', icon: '📚' },
  { id: 'finance', labelKey: 'whatseek.apps.category.finance', icon: '💰' },
  { id: 'life', labelKey: 'whatseek.apps.category.life', icon: '🍵' },
  { id: 'social', labelKey: 'whatseek.apps.category.social', icon: '💬' },
  { id: 'games', labelKey: 'whatseek.apps.category.games', icon: '🎮' },
  { id: 'enterprise', labelKey: 'whatseek.apps.category.enterprise', icon: '🏢' },
  { id: 'agent', labelKey: 'whatseek.apps.category.agent', icon: '🤖' },
] as const;

export const WHATSEEK_CATALOG: readonly WhatseekApp[] = [
  {
    id: 'clip-master',
    name: '剪辑大师',
    summary: '智能视频剪辑：自动粗剪、字幕、配乐，支持多轨道时间线。',
    developer: '问寻工作室',
    category: 'video',
    kind: 'ai',
    icon: '🎬',
    rating: 4.8,
    usersLabel: '2.3万',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['视频剪辑', '字幕', '粗剪'],
    updatedAt: '2026-09-28',
    permissions: ['相册', '麦克风'],
  },
  {
    id: 'image-studio',
    name: '图片工坊',
    summary: 'AI 图片生成与编辑：商品海报、抠图、扩图一站完成。',
    developer: '问寻工作室',
    category: 'image',
    kind: 'ai',
    icon: '🖼️',
    rating: 4.7,
    usersLabel: '1.8万',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['图片生成', '海报', '抠图'],
    updatedAt: '2026-09-25',
    permissions: ['相册'],
  },
  {
    id: 'xhs-title',
    name: '小红书标题生成器',
    summary: '爆款标题一键生成：输入主题，输出 10 条高点击标题。',
    developer: '创作者小队',
    category: 'marketing',
    kind: 'ai',
    icon: '✍️',
    rating: 4.6,
    usersLabel: '9562',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['小红书', '标题', '文案'],
    updatedAt: '2026-09-20',
    permissions: [],
  },
  {
    id: 'crm-manager',
    name: '客户管家 CRM',
    summary: '轻量客户管理：客户列表、跟进记录、标签与统计看板。',
    developer: '云途软件',
    category: 'enterprise',
    kind: 'web',
    icon: '🤝',
    rating: 4.5,
    usersLabel: '1.1万',
    priceLabel: '¥12/月',
    aiCapability: true,
    tags: ['客户管理', 'CRM', '销售'],
    updatedAt: '2026-09-18',
    permissions: ['联系人'],
  },
  {
    id: 'stock-keeper',
    name: '库存管家',
    summary: '进销存一体化：入库、出库、盘点与库存预警。',
    developer: '云途软件',
    category: 'enterprise',
    kind: 'web',
    icon: '📦',
    rating: 4.4,
    usersLabel: '7312',
    priceLabel: '¥8/月',
    aiCapability: false,
    tags: ['库存', '进销存', '仓库'],
    updatedAt: '2026-09-12',
    permissions: [],
  },
  {
    id: 'cross-border-picker',
    name: '跨境选品助手',
    summary: '跨境选品雷达：趋势品类、竞品价格、利润测算。',
    developer: '出海工具集',
    category: 'ecommerce',
    kind: 'ai',
    icon: '🚢',
    rating: 4.6,
    usersLabel: '1.5万',
    priceLabel: '订阅 ¥29/月',
    aiCapability: true,
    tags: ['跨境', '选品', '电商'],
    updatedAt: '2026-09-30',
    permissions: [],
  },
  {
    id: 'site-builder',
    name: '独立站搭建器',
    summary: '30 分钟搭好独立站：首页、商品页、购物车、订单模板齐全。',
    developer: '出海工具集',
    category: 'ecommerce',
    kind: 'web',
    icon: '🏗️',
    rating: 4.3,
    usersLabel: '6891',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['独立站', '建站', '电商'],
    updatedAt: '2026-09-08',
    permissions: [],
  },
  {
    id: 'meeting-notes',
    name: '会议纪要助手',
    summary: '录音转纪要：自动区分发言人，输出待办清单。',
    developer: '效率引擎',
    category: 'office',
    kind: 'ai',
    icon: '📝',
    rating: 4.7,
    usersLabel: '3.4万',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['会议', '纪要', '转写'],
    updatedAt: '2026-09-29',
    permissions: ['麦克风', '文件'],
  },
  {
    id: 'code-mate',
    name: '代码助手',
    summary: 'AI 结对编程：补全、解释、重构、单测生成。',
    developer: 'BirdCoder',
    category: 'coding',
    kind: 'ai',
    icon: '💻',
    rating: 4.9,
    usersLabel: '5.6万',
    priceLabel: '订阅 ¥20/月',
    aiCapability: true,
    tags: ['编程', 'AI', '单测'],
    updatedAt: '2026-10-01',
    permissions: ['文件'],
  },
  {
    id: 'audio-scribe',
    name: '音频转写',
    summary: '音频转文字：中英混合识别，支持导出 SRT 字幕。',
    developer: '效率引擎',
    category: 'audio',
    kind: 'ai',
    icon: '🎧',
    rating: 4.5,
    usersLabel: '1.2万',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['转写', '字幕', '音频'],
    updatedAt: '2026-09-15',
    permissions: ['麦克风', '文件'],
  },
  {
    id: 'ledger-lite',
    name: '轻记账',
    summary: '极简记账：拍照记一笔，自动分类月度报表。',
    developer: '生活小队',
    category: 'finance',
    kind: 'mini',
    icon: '💰',
    rating: 4.4,
    usersLabel: '2.9万',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['记账', '财务', '报表'],
    updatedAt: '2026-09-10',
    permissions: ['相册'],
  },
  {
    id: 'schedule-pro',
    name: '日程管家',
    summary: '日程管理：自然语言建日程，多端提醒不遗漏。',
    developer: '效率引擎',
    category: 'efficiency',
    kind: 'web',
    icon: '📅',
    rating: 4.6,
    usersLabel: '2.1万',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['日程', '提醒', '效率'],
    updatedAt: '2026-09-22',
    permissions: ['通知'],
  },
  {
    id: 'study-notes',
    name: '学习笔记',
    summary: 'AI 学习笔记：划线摘录自动整理成知识卡片。',
    developer: '教育实验室',
    category: 'education',
    kind: 'ai',
    icon: '📚',
    rating: 4.5,
    usersLabel: '8734',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['笔记', '学习', '知识卡'],
    updatedAt: '2026-09-05',
    permissions: [],
  },
  {
    id: 'city-bites',
    name: '附近探店',
    summary: '发现附近好店：真实评价、人均与排队情况。',
    developer: '生活小队',
    category: 'life',
    kind: 'external',
    icon: '🍵',
    rating: 4.2,
    usersLabel: '4.7万',
    priceLabel: '免费',
    aiCapability: false,
    tags: ['探店', '美食', '附近'],
    updatedAt: '2026-08-30',
    permissions: ['地理位置'],
  },
  {
    id: 'interest-clubs',
    name: '兴趣社群',
    summary: '找到同好：读书会、爬山队、桌游局，一键加入。',
    developer: '社群科技',
    category: 'social',
    kind: 'web',
    icon: '💬',
    rating: 4.1,
    usersLabel: '1.9万',
    priceLabel: '免费',
    aiCapability: false,
    tags: ['社群', '兴趣', '活动'],
    updatedAt: '2026-08-26',
    permissions: ['通知'],
  },
  {
    id: 'game-center',
    name: '棋牌游戏中心',
    summary: '斗地主、麻将、象棋，随时开局。',
    developer: '游戏工坊',
    category: 'games',
    kind: 'web',
    icon: '🎮',
    rating: 4.0,
    usersLabel: '6.8万',
    priceLabel: '免费',
    aiCapability: false,
    tags: ['棋牌', '游戏', '休闲'],
    updatedAt: '2026-09-01',
    permissions: [],
  },
  {
    id: 'contract-review',
    name: '合同审查助手',
    summary: 'AI 合同审查：风险条款标注、缺失条款提示。',
    developer: '企业服务社',
    category: 'enterprise',
    kind: 'ai',
    icon: '📜',
    rating: 4.7,
    usersLabel: '5120',
    priceLabel: '企业授权',
    aiCapability: true,
    tags: ['合同', '法务', '审查'],
    updatedAt: '2026-09-26',
    permissions: ['文件'],
  },
  {
    id: 'data-board',
    name: '数据看板',
    summary: '业务数据一屏掌握：指标卡、趋势图、异常提醒。',
    developer: '云途软件',
    category: 'office',
    kind: 'web',
    icon: '📊',
    rating: 4.5,
    usersLabel: '1.6万',
    priceLabel: '¥15/月',
    aiCapability: true,
    tags: ['数据', '看板', '统计'],
    updatedAt: '2026-09-24',
    permissions: [],
  },
  {
    id: 'news-agent',
    name: '行业新闻整理 Agent',
    summary: '每天定时整理行业新闻摘要，推送到消息中心。',
    developer: '问寻官方',
    category: 'agent',
    kind: 'agent',
    icon: '🤖',
    rating: 4.8,
    usersLabel: '9863',
    priceLabel: '免费',
    aiCapability: true,
    tags: ['Agent', '新闻', '定时任务'],
    updatedAt: '2026-09-27',
    permissions: ['通知'],
  },
] as const;

/** Keyword → module plan used by the AI creation flow (PRD §17/§19). */
const CREATION_MODULE_PLANS: readonly { match: readonly string[]; modules: readonly string[] }[] = [
  { match: ['库存', '进销存', '仓库'], modules: ['商品入库', '出库管理', '库存盘点', '库存预警', '库存统计'] },
  { match: ['客户', 'crm', '销售'], modules: ['客户列表', '客户详情', '跟进记录', '标签', '搜索', '数据统计'] },
  { match: ['独立站', '商城', '卖', '电商', '店铺'], modules: ['首页', '商品页', '购物车', '订单', '客户管理', '营销页面'] },
  { match: ['订单', 'order'], modules: ['订单列表', '订单详情', '发货管理', '售后'] },
  { match: ['会员', 'member'], modules: ['会员等级', '权益管理', '积分规则'] },
  { match: ['支付', 'pay'], modules: ['收银台', '支付渠道', '对账'] },
  { match: ['待办', '任务', 'todo'], modules: ['任务列表', '任务详情', '提醒'] },
  { match: ['笔记', 'notes', '知识'], modules: ['笔记列表', '编辑器', '标签', '搜索'] },
];

export const DEFAULT_CREATION_MODULES: readonly string[] = ['首页', '列表', '详情', '设置', '数据统计'];

export function planModulesForRequirement(requirement: string): string[] {
  const lower = requirement.toLowerCase();
  const matched = new Set<string>();
  for (const plan of CREATION_MODULE_PLANS) {
    if (plan.match.some((keyword) => lower.includes(keyword))) {
      for (const moduleName of plan.modules) {
        matched.add(moduleName);
      }
    }
  }
  if (matched.size === 0) {
    return [...DEFAULT_CREATION_MODULES];
  }
  return [...matched];
}
