#!/usr/bin/env node
/**
 * Mini-program runtime bundler (MINI_PROGRAM_APP_ARCHITECTURE_SPEC §Commands):
 * bundles `src/bootstrap/runtime.ts` into the CommonJS runtime document the
 * WeChat runtime requires (`src/runtime/app.js`) with the selected deployment
 * profile injected as `__SDKWORK_RUNTIME_ENV__`.
 *
 * Usage: node scripts/build-runtime.mjs [--deployment-profile standalone|cloud]
 *                                     [--environment development|test|staging|production]
 *                                     [--watch]
 */

import { build, context } from 'esbuild';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const surfaceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function parseArgs(argv) {
  const options = { deploymentProfile: 'standalone', environment: 'development', watch: false };
  for (let index = 0; index < argv.length; index += 1) {
    if (argv[index] === '--deployment-profile') options.deploymentProfile = argv[++index];
    else if (argv[index] === '--environment') options.environment = argv[++index];
    else if (argv[index] === '--watch') options.watch = true;
    else throw new Error(`unsupported option: ${argv[index]}`);
  }
  return options;
}

function loadRuntimeEnv(deploymentProfile, environment) {
  const profileId = `${deploymentProfile}.${environment}`;
  const sourcePath = path.join(surfaceRoot, 'config', 'mini-program', `runtime-env.${profileId}.json`);
  if (!existsSync(sourcePath)) {
    throw new Error(`runtime-env source missing for ${profileId}: ${sourcePath}`);
  }
  const value = JSON.parse(readFileSync(sourcePath, 'utf8'));
  if (value.profileId !== profileId || value.runtimeTarget !== 'mini-program') {
    throw new Error(`runtime-env identity mismatch for ${profileId}`);
  }
  return value;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const runtimeEnv = loadRuntimeEnv(options.deploymentProfile, options.environment);
  const entry = path.join(surfaceRoot, 'src', 'bootstrap', 'runtime.ts');
  const outfile = path.join(surfaceRoot, 'src', 'runtime', 'app.js');
  mkdirSync(path.dirname(outfile), { recursive: true });

  const buildOptions = {
    entryPoints: [entry],
    outfile,
    bundle: true,
    format: 'cjs',
    platform: 'neutral',
    target: 'es2021',
    define: {
      __SDKWORK_RUNTIME_ENV__: JSON.stringify(runtimeEnv),
      'process.env.NODE_ENV': '"production"',
    },
    logLevel: 'info',
  };

  if (options.watch) {
    const ctx = await context(buildOptions);
    await ctx.watch();
    console.log('[build-runtime] watching…');
    return;
  }
  await build(buildOptions);
  // Runtime-env mirror consumed by pages that need the profile identity.
  writeFileSync(
    path.join(surfaceRoot, 'src', 'runtime', 'runtime-env.js'),
    `// Generated by scripts/build-runtime.mjs — do not edit.\nmodule.exports = ${JSON.stringify(runtimeEnv, null, 2)};\n`,
  );
  console.log(`[build-runtime] ${runtimeEnv.profileId} -> src/runtime/app.js`);
}

main().catch((error) => {
  console.error('[build-runtime] failed:', error instanceof Error ? error.message : error);
  process.exit(1);
});
